package store

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v5"
)

// PolicyStore records only an adult assertion and acknowledged document versions.
// Timestamps are generated by the server; no date of birth, ID, location or IP is collected.
type PolicyStore interface {
	CreateUserWithPolicies(context.Context, string, string, string, string) (User, error)
	AcceptPolicies(context.Context, string, string, string) (User, error)
}

const userColumns = `id,email,password_hash,role,email_verified,token_version,adult_confirmed_at,terms_version,privacy_version,policies_accepted_at`

func userDestinations(u *User) []any {
	return []any{&u.ID, &u.Email, &u.PasswordHash, &u.Role, &u.EmailVerified, &u.TokenVersion, &u.AdultConfirmedAt, &u.TermsVersion, &u.PrivacyVersion, &u.PoliciesAcceptedAt}
}

// Registration and policy acknowledgment commit in one statement: a failed
// acknowledgment cannot leave an apparently registered hosted account behind.
func (s *Store) CreateUserWithPolicies(ctx context.Context, email, passwordHash, terms, privacy string) (User, error) {
	var u User
	err := s.Pool.QueryRow(ctx, `INSERT INTO users(id,email,password_hash,adult_confirmed_at,terms_version,privacy_version,policies_accepted_at)
 VALUES($1,$2,$3,now(),$4,$5,now()) RETURNING `+userColumns, NewID(), email, passwordHash, terms, privacy).Scan(userDestinations(&u)...)
	return u, err
}

func (s *Store) AcceptPolicies(ctx context.Context, uid, terms, privacy string) (User, error) {
	var u User
	err := s.Pool.QueryRow(ctx, `UPDATE users SET adult_confirmed_at=COALESCE(adult_confirmed_at,now()),
 policies_accepted_at=CASE WHEN terms_version=$2 AND privacy_version=$3 AND adult_confirmed_at IS NOT NULL THEN COALESCE(policies_accepted_at,now()) ELSE now() END,
 terms_version=$2,privacy_version=$3 WHERE id=$1 RETURNING `+userColumns, uid, terms, privacy).Scan(userDestinations(&u)...)
	if errors.Is(err, pgx.ErrNoRows) {
		return u, ErrNotFound
	}
	return u, err
}
