CREATE TABLE users (id TEXT PRIMARY KEY, email TEXT NOT NULL UNIQUE, data TEXT NOT NULL CHECK(json_valid(data)), settings TEXT NOT NULL DEFAULT '{}' CHECK(json_valid(settings)));
CREATE TABLE interview_configs (user_id TEXT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE, data TEXT NOT NULL CHECK(json_valid(data)));
CREATE TABLE auth_actions (token_hash TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, purpose TEXT NOT NULL, expires_at INTEGER NOT NULL, created_at INTEGER NOT NULL, UNIQUE(user_id,purpose));
CREATE TABLE resumes (id TEXT PRIMARY KEY, user_id TEXT NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE, data TEXT NOT NULL CHECK(json_valid(data)));
CREATE TABLE resume_reviews (id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, resume_id TEXT REFERENCES resumes(id) ON DELETE SET NULL, provider TEXT NOT NULL, model TEXT NOT NULL, result TEXT NOT NULL CHECK(json_valid(result)), created_at INTEGER NOT NULL);
CREATE TABLE sessions (id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, status TEXT NOT NULL, created_at INTEGER NOT NULL, data TEXT NOT NULL CHECK(json_valid(data)));
CREATE INDEX sessions_owner_created ON sessions(user_id,created_at DESC);
CREATE INDEX sessions_state ON sessions(status,created_at);
CREATE TABLE transcript_turns (sequence INTEGER PRIMARY KEY AUTOINCREMENT, id TEXT NOT NULL UNIQUE, session_id TEXT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE, event_id TEXT, meta TEXT NOT NULL CHECK(json_valid(meta)), data TEXT NOT NULL CHECK(json_valid(data)), UNIQUE(session_id,event_id));
CREATE INDEX transcript_session ON transcript_turns(session_id,sequence);
CREATE TABLE workspace_snapshots (sequence INTEGER PRIMARY KEY AUTOINCREMENT, session_id TEXT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE, revision INTEGER NOT NULL, ts_ms INTEGER NOT NULL, data TEXT NOT NULL CHECK(json_valid(data)), UNIQUE(session_id,revision));
CREATE TABLE canvas_snapshots (sequence INTEGER PRIMARY KEY AUTOINCREMENT, session_id TEXT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE, ts_ms INTEGER NOT NULL, elements TEXT NOT NULL CHECK(json_valid(elements)), image_ref TEXT NOT NULL);
CREATE TABLE behavior_samples (sequence INTEGER PRIMARY KEY AUTOINCREMENT, session_id TEXT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE, ts_ms INTEGER NOT NULL, data TEXT NOT NULL CHECK(json_valid(data)), created_at INTEGER NOT NULL);
CREATE INDEX behavior_session ON behavior_samples(session_id);
CREATE TABLE events (sequence INTEGER PRIMARY KEY AUTOINCREMENT, session_id TEXT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE, ts_ms INTEGER NOT NULL, kind TEXT NOT NULL, data TEXT NOT NULL CHECK(json_valid(data)), created_at INTEGER NOT NULL);
CREATE INDEX events_session ON events(session_id);
CREATE TABLE reports (session_id TEXT PRIMARY KEY REFERENCES sessions(id) ON DELETE CASCADE, data TEXT NOT NULL CHECK(json_valid(data)));
CREATE TABLE scores (session_id TEXT PRIMARY KEY REFERENCES sessions(id) ON DELETE CASCADE, data TEXT NOT NULL CHECK(json_valid(data)));
CREATE TABLE scoring_jobs (session_id TEXT PRIMARY KEY REFERENCES sessions(id) ON DELETE CASCADE, status TEXT NOT NULL, created_at INTEGER NOT NULL, data TEXT NOT NULL CHECK(json_valid(data)));
CREATE INDEX scoring_job_status ON scoring_jobs(status,created_at);
CREATE TABLE session_credentials (session_id TEXT PRIMARY KEY REFERENCES sessions(id) ON DELETE CASCADE, ciphertext BLOB NOT NULL, expires_at INTEGER NOT NULL);
-- The allowance ledger deliberately survives session deletion, as on the hosted service.
CREATE TABLE interview_usage (session_id TEXT PRIMARY KEY, identity TEXT NOT NULL, funding TEXT NOT NULL, activated_at INTEGER NOT NULL, tester_exempt INTEGER NOT NULL DEFAULT 0);
CREATE INDEX usage_identity ON interview_usage(identity,activated_at);
CREATE TABLE interview_feedback (session_id TEXT PRIMARY KEY REFERENCES sessions(id) ON DELETE CASCADE, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, data TEXT NOT NULL CHECK(json_valid(data)));
CREATE TABLE feedback (id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, created_at INTEGER NOT NULL, data TEXT NOT NULL CHECK(json_valid(data)));
CREATE TABLE tester_emails (email TEXT PRIMARY KEY, data TEXT NOT NULL CHECK(json_valid(data)));
CREATE TABLE beta_applications (id TEXT NOT NULL UNIQUE, user_id TEXT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE, created_at INTEGER NOT NULL, reviewed_by TEXT NOT NULL DEFAULT '', data TEXT NOT NULL CHECK(json_valid(data)));
CREATE TABLE template_requests (id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, created_at INTEGER NOT NULL, reviewed_by TEXT NOT NULL DEFAULT '', data TEXT NOT NULL CHECK(json_valid(data)));
CREATE TABLE shared_interview_results (id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, source TEXT NOT NULL, client_session_id TEXT NOT NULL, updated_at INTEGER NOT NULL, data TEXT NOT NULL CHECK(json_valid(data)), UNIQUE(user_id,source,client_session_id));
