import { StyleSheet } from "react-native";

export const colors = {
  studio: "#f6f7f3",
  panel: "#ffffff",
  soft: "#edf2eb",
  line: "#d6dfd4",
  ink: "#22372c",
  muted: "#526356",
  accent: "#2d6445",
  leaf: "#c5ddad",
  warm: "#f4ead7",
  danger: "#a13636",
};
export const s = StyleSheet.create({
  root: { flex: 1, backgroundColor: colors.studio },
  frame: {
    flex: 1,
    width: "100%",
    maxWidth: 540,
    alignSelf: "center",
    backgroundColor: colors.studio,
  },
  page: { paddingHorizontal: 24, paddingTop: 22, paddingBottom: 28, gap: 24 },
  row: { flexDirection: "row", alignItems: "center", gap: 12 },
  between: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  grow: { flex: 1 },
  title: {
    fontSize: 32,
    lineHeight: 37,
    fontWeight: "600",
    letterSpacing: -1.25,
    color: colors.ink,
  },
  h2: {
    fontSize: 20,
    fontWeight: "600",
    letterSpacing: -0.4,
    color: colors.ink,
  },
  h3: { fontSize: 16, fontWeight: "600", color: colors.ink, lineHeight: 23 },
  text: { fontSize: 15, lineHeight: 23, color: colors.ink },
  muted: { fontSize: 14, lineHeight: 21, color: colors.muted },
  small: { fontSize: 12, lineHeight: 18, color: colors.muted },
  eyebrow: {
    fontSize: 10,
    letterSpacing: 1.5,
    fontWeight: "700",
    color: colors.accent,
  },
  card: {
    backgroundColor: colors.panel,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 20,
    padding: 20,
    gap: 12,
  },
  soft: { backgroundColor: colors.soft, borderRadius: 16, padding: 18, gap: 8 },
  button: {
    minHeight: 52,
    borderRadius: 14,
    paddingHorizontal: 20,
    paddingVertical: 14,
    backgroundColor: colors.accent,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
  },
  buttonText: {
    flexShrink: 1,
    textAlign: "center",
    fontSize: 15,
    fontWeight: "600",
    color: "#fff",
  },
  ghost: { backgroundColor: colors.soft },
  ghostText: { color: colors.accent },
  iconButton: {
    minWidth: 46,
    minHeight: 46,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 23,
  },
  iconBox: {
    width: 46,
    height: 46,
    borderRadius: 15,
    backgroundColor: colors.soft,
    alignItems: "center",
    justifyContent: "center",
  },
  input: {
    backgroundColor: colors.panel,
    borderColor: colors.line,
    borderWidth: 1,
    borderRadius: 16,
    padding: 16,
    fontSize: 16,
    lineHeight: 25,
    color: colors.ink,
    minHeight: 130,
    textAlignVertical: "top",
  },
  divider: { height: 1, backgroundColor: colors.line },
  section: { gap: 12 },
  chip: {
    minHeight: 44,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 22,
    paddingHorizontal: 17,
    paddingVertical: 11,
    alignItems: "center",
    justifyContent: "center",
  },
  chipActive: { backgroundColor: colors.ink, borderColor: colors.ink },
  nav: {
    flexDirection: "row",
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: colors.line,
    backgroundColor: colors.panel,
  },
  navItem: {
    flex: 1,
    minHeight: 60,
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
  },
  navText: { fontSize: 11, fontWeight: "500", color: colors.muted },
  coachBubble: {
    backgroundColor: colors.panel,
    padding: 22,
    borderRadius: 22,
    borderTopLeftRadius: 4,
    borderWidth: 1,
    borderColor: colors.line,
    gap: 14,
  },
  answerBubble: {
    backgroundColor: colors.soft,
    padding: 20,
    borderRadius: 22,
    borderBottomRightRadius: 4,
    gap: 10,
    marginLeft: 22,
  },
  alert: {
    backgroundColor: "#fff1df",
    padding: 12,
    borderRadius: 12,
    color: "#764d18",
    fontSize: 13,
    lineHeight: 19,
  },
});
